### ISSUE TITLE
Expose App `localizationsDelegates` property

### ISSUE THREAD

**Issue by DavidRG13** [ookami-kb/storybook_flutter#11]
Would it make any sense to expose this App `localizationsDelegates` in `Storybook`?

We are using `FlutterI18n` and have some widgets configured to use translations, making it impossible for us to use storybook for those widgets.

Great project!

**Comment by ookami-kb** [comment]
Thanks!

Yeah, I guess it makes total sense.

**Comment by DavidRG13** [comment]
Cool, do you want me to raise a PR?

**Comment by ookami-kb** [comment]
Yep, that would be great 👍

**Comment by DavidRG13** [comment]
@ookami-kb , thanks for checking and merging the PR!

When could we expect a new release? No rush, just to be aware ;)

**Comment by ookami-kb** [comment]
Thank you for the PR!

Just released :)
