### ISSUE TITLE
Join forces with dashbook?

### ISSUE THREAD

**Issue by MuathAmer** [ookami-kb/storybook_flutter#16]
Let's make one great flutter dev-tool instead of many!

Hi! first of all, I want to say that I really appreciate the works in this open-source project, I installed it and all other similar packages, and I think it can be great if the work is unified into a single tool which can become popular and a standard for flutter development. 

I will list all the projects that I found here:
- https://github.com/erickzanardo/dashbook
- https://github.com/ookami-kb/storybook_flutter
- https://github.com/ilikerobots/storyboard

These 3 have the same goal, a storybookjs inspired package to showcase flutter widgets.

But there are also these projects that if combined with a flutter storybook, can really become a standard tool for every flutter developer:
- https://github.com/jamesblasco/flutter_preview (preview any widget in vs code)
- https://github.com/aloisdeniel/flutter_device_preview (emulate any device size)
- https://github.com/rodydavis/storyboard (see all routes at once)

I am pasting this same issue to all of these projects, if you don't want it, feel free to close it :D

Tell me what you think!

**Comment by ookami-kb** [comment]
I'm planning to continue working on this repo, but I'm always open to feature requests and PRs.
