### ISSUE TITLE
Visualizing stories on device preview

### ISSUE THREAD

**Issue by gcostaapps** [ookami-kb/storybook_flutter#23]
Is there a way to visualize the stories using [device preview](https://pub.dev/packages/device_preview)? 

I've tried to add this line to Storybook but the entire page gets wrapped inside device_preview, not only the storyh

```
 storyWrapperBuilder: (context, story, widget) =>
            DevicePreview.appBuilder(context, widget)
```

**Comment by ookami-kb** [comment]
I don't think that it's possible at the moment. But it looks like an interesting use case, I'll think about what can be done to support it.

**Comment by ookami-kb** [comment]
I've refactored the storybook to allow more customization options and uploaded a [plugin](https://pub.dev/packages/storybook_device_preview) for `device_preview`. Let me know if it solves your usecase.

**Comment by gcostaapps** [comment]
Thank you for the fast feedback and solution, I think it's great and it do solves my usecases!
