### ISSUE TITLE
Feature request: online demo

### ISSUE THREAD

**Issue by roman-petrov** [ookami-kb/storybook_flutter#27]
First, I think it is a great idea to make create such package for Flutter (reserved name is great through :) What about publishing online demo (for example, into GitHub pages)? In my opinion, it is easier for new users to see all features in packages which have online demos. In this case they do not need to clone/build package and can see it working in one single click.

Also, I think, it would be quite simple to publish online demo to GitHub pages if you already have an example.

**Comment by ookami-kb** [comment]
Thank you! Yeah, makes total sense for me.

**Comment by ookami-kb** [comment]
Done: https://ookami-kb.github.io/storybook_flutter/
