### ISSUE TITLE
Expose MaterialApp  navigatorObservers and builder

### ISSUE THREAD

**Issue by JasonHezz** [ookami-kb/storybook_flutter#34]
I'm using [bot_toast](https://github.com/MMMzq/bot_toast)
![image](https://user-images.githubusercontent.com/15358765/127378534-1679bb1c-4291-4bab-a79f-2b208e41b1ae.png)

In it's new version, I need pass BotToastInit BotToastNavigatorObserver. Could you please add this feature?

**Comment by ookami-kb** [comment]
Yeah, makes sense to me, will take a look.

**Comment by ookami-kb** [comment]
Done in `0.5.1`.
