### ISSUE TITLE
Feature Request: Int return value for slider knob

### ISSUE THREAD

**Issue by joshpetit** [ookami-kb/storybook_flutter#36]
Thanks for making this amazing package, it's a real big help :)

A small feature that would be nice to have is the ability to make the `slider` return an integer rather than double. It is possible to cast the value returned to an int, but making the slider capable of only returning integers would be nice. If you don't have much down time I'd be willing to implement this with guidance on how you'd like the API to look.

Thanks again for this package!

**Comment by ookami-kb** [comment]
Thanks!

Yeah, makes sense to me, I think we even had some use case for it as well, so I'll try to take a look at it in the near future.
