### ISSUE TITLE
Discussion: Testing Features Support

### ISSUE THREAD

**Issue by searchy2** [ookami-kb/storybook_flutter#37]
Thank you for such a great library which I use heavily in all my projects.

Recently, I've setup golden_toolkit to automatically generate screenshots. However, this doesn't make sense if one is already using this library. The issue is that `golden_toolkit` requires extensive setup and is limited by widget test limitations. Since our UI is already storyboarded, it makes more sense to run tests from this library instead.

Do you have any plans to add testing features? 
There are a few testing features I'm immediately interested in adding to storyboard:
1. Automatically iterate through all stories and capture screenshots. 
2. Automatically generate different screensize previews. 
3. A knob options wrapper for automatically testing different scenarios of knob values. If the knob values are added to a map, they can be automatically iterated through to generate all the combinations of UI states.

What are your thoughts?

**Comment by ookami-kb** [comment]
Thank you, I'm glad you like it!

Yes, it was my plan to add something like that from the very beginning. Unfortunately, I didn't have much time recently, but I'm definitely going to work on that in the (hopefully, near) future. I was thinking about similar use cases, so thanks for putting them into the written form – now we have an issue to start with 😄
