### ISSUE TITLE
Cannot use knobs in MacOS

### ISSUE THREAD

**Issue by bahamut657** [ookami-kb/storybook_flutter#43]
Flutter: 2.5.1
Storybook version: 0.7.0
OS: MacOS BigSur

Running storybook on MacOS results in unusable knobs.
Same sources works from Web

**Comment by ookami-kb** [comment]
I've found one issue with scrollbars on macOS. Can you please check if the latest version solves your problem?

**Comment by bahamut657** [comment]
Thank you so much. 
Now it seems to work correctly.
