### ISSUE TITLE
CupertinoApp

### ISSUE THREAD

**Issue by pavlouha** [ookami-kb/storybook_flutter#44]
Hello, are there any plans of adding CupertinoApp inside Storybook?

**Comment by ookami-kb** [comment]
Hey, not really. It will just change the look of things like knobs etc. The story itself can contain cupertino widgets, of course.

Do you have some specific use case for cupertino app?

**Comment by Pavlouha** [comment]
Yes, my Cupertino-based widgets have wrong colors from MaterialTheme instead of CupertinoTheme. I wrap them into CupertinoApp and do some tricks for correct Navigator work.

**Comment by ookami-kb** [comment]
I think you can just provide the `storyWrapperBuilder` with `CupertinoTheme`, something like this:

```dart
Storybook(
  storyWrapperBuilder: (context, story, child) => CupertinoTheme(
    data: const CupertinoThemeData(),
    child: Container(
      color: story.background,
      padding: story.padding,
      child: Center(child: child),
    ),
  ),
  children: [
    // ...
  ],
)
```

**Comment by Pavlouha** [comment]
After Navigator pushes, e. g. showCupertinoModalPopup(), it's necessary to wrap showed ​widgets in CupertinoTheme. Is there a way not to do this?

**Comment by ookami-kb** [comment]
Try providing `builder` parameter to the `Storybook` in that case:

```dart
builder: (context, child) => CupertinoTheme(
  data: const CupertinoThemeData(primaryColor: Colors.green),
  child: child!,
),
```

**Comment by Pavlouha** [comment]
Thanks a lot, all of my Cupertino widgets are working now)

**Comment by Pavlouha** [comment]
I found another issue. I had overridden Cupertino text theme to custom fonts and now see yellow lines under some Text widgets(
Widget inside my app:
![image](https://user-images.githubusercontent.com/28784325/135085521-312d0dee-8f73-4d99-8f0e-7b32accee552.png)
Widget inside StoryBook:
![image](https://user-images.githubusercontent.com/28784325/135086176-93516241-41b6-447b-88c6-e426ff4ba612.png)

**Comment by ookami-kb** [comment]
Hard to say something, looks like some elements lack theming at all. Can you please provide a full reproducible example?

**Comment by Pavlouha** [comment]
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:storybook_flutter/storybook_flutter.dart';

void main() async {
  runApp(
    const _MainWidget(),
  );
}

class _MainWidget extends StatelessWidget {
  const _MainWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Storybook(
      children: [
        Story(
          name: "CupertinoDateRangePicker",
          builder: (c, k) => CupertinoButton(
            onPressed: () {
              showCupertinoModalPopup(
                context: c,
                builder: (BuildContext context) {
                  return SizedBox(
                    height: 200,
                    child: Container(
                      alignment: Alignment.topCenter,
                      color: CupertinoTheme.of(c).scaffoldBackgroundColor,
                      child: Text(
                        "Yellow lines under Text",
                        style: CupertinoTheme.of(c).textTheme.textStyle,
                      ),
                    ),
                  );
                },
              );
            },
            child: const Text("Open"),
          ),
        ),
      ],
      theme: ThemeData.light().copyWith(
        appBarTheme: const AppBarTheme(
          color: Colors.white,
          foregroundColor: Colors.black,
        ),
      ),
      darkTheme: ThemeData.dark(),
      storyWrapperBuilder: (context, story, child) => CupertinoPageScaffold(
        child: SafeArea(
          child: Center(
            child: child,
          ),
        ),
      ),
      builder: (context, child) => CupertinoTheme(
        data: CupertinoThemeData(
          scaffoldBackgroundColor: CupertinoColors.black,
          textTheme: CupertinoTheme.of(context).textTheme.copyWith(
                textStyle: GoogleFonts.montserrat(
                  fontSize: 17,
                  letterSpacing: -0.41,
                  color: CupertinoColors.white,
                ),
              ),
        ),
        child: child!,
      ),
    );
  }
}
```

dependencies:
storybook_flutter: ^0.7.0+1
google_fonts: ^2.1.0

**Comment by ookami-kb** [comment]
Yeah, that can be tricky. I have an idea how can it be solved in the library, let me check my guess and come back to you later.

**Comment by ilexbor** [comment]
@ookami-kb Any news on this issue?

**Comment by Pavlouha** [comment]
Hello again) How is the work going?

**Comment by ookami-kb** [comment]
hey, need to resolve some issues with navigation, hopefully will release a preview version soon :)

**Comment by jale-codex** [comment]
Hey there, how's it been? Any rough estimate on when the fix will be ready?

**Comment by ookami-kb** [comment]
Hey, it's currently available as a [preview](https://pub.dev/packages/storybook_flutter/versions/0.9.0-dev.1) – I'm testing it on my projects, updating documentation, and preparing a release.

**Comment by ookami-kb** [comment]
New version is out with a completely separated story interface from the rest of the storybook.

**Comment by pavlouha** [comment]
Cool)
