### ISSUE TITLE
Freezed update

### ISSUE THREAD

**Issue by egorikem** [ookami-kb/storybook_flutter#54]
Hi, @ookami-kb 

Could you be so kind to update the version of `freezed` you are using? 

Currently I'm getting this error:
`storybook_flutter 0.7.0+1 depends on freezed_annotation ^0.14.1` 

This is quite an old feature (current is `1.0.0`) and it will be nice to have the most up to date on! Thanks in advance!

**Comment by diegog-sf** [comment]
Hello, not just freezed all dependencies would be awesome!
I'm specially looking for `device_frame`

**Comment by ookami-kb** [comment]
Yeah, makes sense, will do.

**Comment by ookami-kb** [comment]
I've bumped `device_frame` to `^0.6.0` and `freezed_annotation` to `^0.15.0` (cannot bump it to `1.0.0` since it conflicts with `device_frame`).

**Comment by egorikem** [comment]
There's a little difference between `0.15.0` and `1.0.0`. Thank you very much!

**Comment by egorikem** [comment]
Hi there, @ookami-kb ! As far as I can tell, `device_frame` has updated `freezed` to `1.0.0`. Could you update your package as well?

**Comment by jale-codex** [comment]
Hi, @ookami-kb ! Any news on the update?

**Comment by ookami-kb** [comment]
Heym `device_frame` has some breaking changes in the latest version, so I didn't change it for now.

Next major `storybook_flutter` version with refactored API will have it bumped.
