### ISSUE TITLE
Expose supportedLocales parameter

### ISSUE THREAD

**Issue by bahamut657** [ookami-kb/storybook_flutter#56]
Hi
In order to perform some tests using the Flutter localizations I need to pass 2 parameters:
 - localizationDelegates, currently supported
 - supportedLocales, the list of supported Locales (currently not available)

You can find more info here https://docs.flutter.dev/development/accessibility-and-localization/internationalization

Is it possible to expose this parameter?

Regards and great work!!!

**Comment by ookami-kb** [comment]
Hi, thanks!

Yeah, it makes sense. I can do it later, or feel free to submit a PR.

**Comment by ookami-kb** [comment]
In the new version, the storybook doesn't use MaterialApp for its own interface, so you can just provide your own instance of `MaterialApp` with all the needed parameters as a wrapper.
