### ISSUE TITLE
How can we hide the knobs panel by default with coding?

### ISSUE THREAD

**Issue by yingshaoxo** [ookami-kb/storybook_flutter#58]
Don't want:

![image](https://user-images.githubusercontent.com/17190829/144556527-3e7cd5be-ba67-4523-93ac-e8df4bc14a52.png)

___

Wanted:

![image](https://user-images.githubusercontent.com/17190829/144556563-7ba1cefe-9040-41f3-afaf-b12274326074.png)

**Comment by ookami-kb** [comment]
Hi, I don't think it's currently possible. I'm working on a new version, where this panel will be hidden by default.

**Comment by yingshaoxo** [comment]
@ookami-kb 

Great, looking forward to your new version of this package.

This is really helpful when we wanna develop some flutter components.

I can support you with money when I get rich (the only problem, for now, I don't have money, so sad

**Comment by yingshaoxo** [comment]
By the way, there also has another feature, which may be good to have:

set the mobile view as default when hot reload. (for example, use desktop chrome to do the mobile web page development.

**Comment by ookami-kb** [comment]
Panel is now hidden by default.
