### ISSUE TITLE
How to customize scaffold title

### ISSUE THREAD

**Issue by soumyamahunt** [ookami-kb/storybook_flutter#63]
The default scaffold title when no widgets selected is `Storybook`, how do I customize this text to something I want.

**Comment by ookami-kb** [comment]
Hey, it's not possible in the current version.

Also, keep in mind that the next version will have no default scaffold at all. You can try the current pre-release version to check how it looks like (although, it has some breaking changes).

**Comment by ookami-kb** [comment]
The new version is released without scaffold.
