### ISSUE TITLE
Feature Request : Widget search bar

### ISSUE THREAD

**Issue by octobrekids** [ookami-kb/storybook_flutter#71]
Hi!
First of all, thank you for this project
It helps easier a lot to manage all the widgets in the project :-)

But I'm facing that it is quite hard to find the widget if I have many widgets.
I have to scroll through all the lists to find the widget.
It would be helpful if there is a search bar at the navigator panel to find a widget.

**Comment by ookami-kb** [comment]
Hi, thanks!

Yeah, makes sense to me. I'll look into it.

**Comment by BischlerBastian** [comment]
That would be really nice!
