### ISSUE TITLE
Demo code no longer works

### ISSUE THREAD

**Issue by simplenotezy** [ookami-kb/storybook_flutter#76]
We tried setting up the repository in our project, but we get error:

```
The named parameter 'stories' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'stories'.dart[undefined_named_parameter](https://dart.dev/diagnostics/undefined_named_parameter)
```

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/3786627/162002395-043e1e0c-1f23-4ee6-8f0a-2e983e296c61.png">

We basically just followed the readme and then got the error. When then also tried copying over the demo code 1:1 and got the same error.

**Comment by ookami-kb** [comment]
Hey, that's weird. What version do you have installed? Can you please share you `pubspec.yaml` and `pubspec.lock`?
