### ISSUE TITLE
Feature request: Add option to close the stories list when a story is selected

### ISSUE THREAD

**Issue by RomanovaPrime** [ookami-kb/storybook_flutter#98]
Please, add an option to authomatically close the OverlayEntry when an item inside ContentsPlugin have been selected. It may gets annoing if the user have to press one additional time on the icon to close the list after select an item.

**Comment by ookami-kb** [comment]
Good point. I don't think it makes sense to make it configurable at all, the contents panel automatically closes the overlay when selected.
